#!/usr/bin/env zsh

alias yl="yarn lint"
alias yb="yarn build"
alias yt="yarn test"
alias yf="yarn fix"

alias brake="bundle exec rake"

alias vim="nvim"
alias vi="nvim"

# tmux
alias t="tmux"
alias ta="t a -t"
alias tls="t ls"
alias tn="t new -t"
alias tk="t kill-ses -t"

function v {
	vim `f $@`
}

function iv {
	vim `sf $@`
}

