#!/usr/bin/env zsh

alias yl="yarn lint"
alias yb="yarn build"
alias yt="yarn test"
alias yf="yarn fix"
alias brake="bundle exec rake"
alias vim="nvim"
alias vi="nvim"

function v {
	vim `f $@`
}

function iv {
	vim `sf $@`
}

