#!/usr/bin/env zsh

# Auto-install antibody
if [ ! -f ~/.zsh/antibody ]; then
  curl -sfL git.io/antibody | sh -s - -b ~/.zsh
fi

# Init antibody
source <(~/.zsh/antibody init)

# Plugins
antibody bundle < ~/.zsh/plugins

# Theme
. ~/.zsh/theme

# Aliases and variables
[ -r ~/.zsh/init ] && . ~/.zsh/init
[ -r ~/.zsh/aliases ] && . ~/.zsh/aliases
[ -r ~/.zsh/variables ] && . ~/.zsh/variables
