set nocompatible

" ALE LINTER
"
let g:ale_sign_column_always = 1
let g:ale_fix_on_save = 1
let g:ale_completion_enabled = 1
let g:ale_completion_tsserver_autoimport = 1
let g:ale_fixers = {
\   '*': ['remove_trailing_lines', 'trim_whitespace'],
\}
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'

" PLUGIN MANAGEMENT

call plug#begin('~/.vim/plugged')

Plug 'ludovicchabant/vim-gutentags'
Plug 'vim-airline/vim-airline'
Plug 'mhartington/oceanic-next'
Plug 'dense-analysis/ale'
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'joshdick/onedark.vim'
Plug 'sheerun/vim-polyglot'
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-sleuth'
Plug 'justinmk/vim-sneak'
Plug 'rhysd/vim-grammarous'

call plug#end()

nmap <Space> <Leader>

syntax enable
filetype plugin on

set showcmd
" set path+=**
" set wildignore+=**/node_modules/**
set wildmode=full
set wildmenu
set backspace=indent,eol,start
set laststatus=2
set noshowmode
set number
set termguicolors

colorscheme OceanicNext " onedark

" SNEAK.VIM
let g:sneak#label = 1

" NERD TREE
let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "*",
    \ "Staged"    : "+",
    \ "Untracked" : "NEW",
    \ "Renamed"   : "➜",
    \ "Unmerged"  : "═",
    \ "Deleted"   : "DEL",
    \ "Dirty"     : "MOD",
    \ "Clean"     : "✔︎",
    \ 'Ignored'   : 'x',
    \ "Unknown"   : "?"
    \ }

let NERDTreeMinimalUI = 1
let NERDTreeDirArrows = 1
let NERDTreeShowHidden = 1
let g:NERDTreeWinSize = 24
let g:NERDTreeDirArrowExpandable = '>'
let g:NERDTreeDirArrowCollapsible = '<'

no <C-j> <C-w>j
no <C-k> <C-w>k
no <C-l> <C-w>l
no <C-h> <C-w>h
nnoremap <silent> <Leader>f :NERDTreeFind<CR>
nnoremap <Leader>n :NERDTreeToggle<Enter>

autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
