source ~/.zsh/antigen

antigen use oh-my-zsh

# Plugins
antigen bundle lukechilds/zsh-nvm
antigen bundle laggardkernel/zsh-thefuck
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle fasd

# Theme
antigen theme sunquan1991/aplos aplos

antigen apply

# Aliases and variables
[ -r ~/.zsh/init ] && . ~/.zsh/init
[ -r ~/.zsh/aliases ] && . ~/.zsh/aliases
[ -r ~/.zsh/variables ] && . ~/.zsh/variables
